### ISSUE TITLE
RuntimeError when accessing productName

### ISSUE THREAD

**Issue by cary-rowen** [mltony/nvda-word-nav#16]
## Problem Description: 
When using the WordNav add-on for NVDA, the function  `isVscodeApp`  encounters a  `RuntimeError`  stating "No version information". This error occurs when attempting to access  `self.appModule.productName` . This issue has been observed under certain conditions where the application's version information might not be available.

I don’t know exactly what caused this problem, because it is a machine within the company and the access rights of the application are restricted.

I encountered this error on my SSH application on Windows.

## Expected Behavior: 
The function should handle such exceptions gracefully without throwing runtime errors, allowing NVDA to continue functioning properly regardless of the application state.

## Actual Behavior: 
A `RuntimeError: No version information` is thrown, which causes the word navigation keys to fail.

**Comment by mltony** [comment]
Could you try to catch that exception in `isVscodeApp` function and return False - that should fix it.
