### ISSUE TITLE
cursor can't read past the first line in html multiline edit fields

### ISSUE THREAD

**Issue by vortex1024** [mltony/nvda-word-nav#3]
str:
1. open:
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_textarea
2. in the second edit field, write:
"
we have to see
why this is not working
"
3. go to the second line.
4. when trying to move with ctrl+left and right arrow, no matter if we use right or left control, the cursor is tuc on the first line, reading only "we have to see" in a loop.

Google Chrome version 87.0.4280.88
NVDA version 2020.3
wordnav 1.2, windows 10 
currently, the workaround I've found is to disable it in chrome.

**Comment by mltony** [comment]
This is due to underlying bug in NVDA:

https://github.com/nvaccess/nvda/issues/11931

Please leave your comment there to increase visibility.

**Comment by vortex1024** [comment]
Got it, done. Is it ok if we leave this open, so I can be notified when it is fixed?

**Comment by mltony** [comment]
Sure, no problem.

**Comment by mltony** [comment]
I did some more investigation on this and managed to drill down to an underlying issue in chromium. I reported that issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1260726

**Comment by mltony** [comment]
I think I found a workaround for this issue. Please check v1.5.

**Comment by vortex1024** [comment]
yes, it works! thanks for the fix
