### ISSUE TITLE
Whether you can consider two matching methods, regular expressions may not be conducive to novices.

### ISSUE THREAD

**Issue by cary-rowen** [mltony/nvda-word-nav#4]
Bulky word navigation in version 1.4 is very friendly to novices, especially in the Chinese environment.
Can you consider supporting both regular expressions and punctuation lists?

Thanks

**Comment by mltony** [comment]
Ok, will add them back. I wasn't sure if anyone was even using them :)

**Comment by cary-rowen** [comment]
Some people around me who don’t master regular expressions are using them. Thank you for your efforts. In addition, can this add-on be registered in the translation system?

**Comment by mltony** [comment]
I just added back bulky word definition in v1.7.

**Comment by cary-rowen** [comment]
Thank you for your hard work, I want to close this Issue now.
